export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export const GET_SITE_DATA = 'GET_SITE_DATA';
export const GET_SITE_DATA_REQUEST = 'GET_SITE_DATA_REQUEST';
export const GET_SITE_DATA_SUCCESS = 'GET_SITE_DATA_SUCCESS';
export const GET_SITE_DATA_FAILURE = 'GET_SITE_DATA_FAILURE';
export const SITE_DATA_FETCHED = 'SITE_DATA_FETCHED';

export const NAVIGATION_HIDE = 'NAVIGATION_HIDE';
export const NAVIGATION_SHOW = 'NAVIGATION_SHOW';

export const ROOT_URL = 'https://www.zamiang.com';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const PAGE_SIZE = 9;
